org: remoteitall
app: zoommate
service: ZoomMate

# Exclude unnecessary files from deployment
package:
  exclude:
    - tests/**
    - README.md
    - .env
    - node_modules/**

provider:
  name: aws
  runtime: nodejs22.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-southeast-2'}
  apiGateway:
    shouldStartNameWithService: true
  logs: 
    restApi: true
  tracing:
    lambda: true
    apiGateway: true
  logRetentionInDays: 14

  # 👉 Provider-level environment variables
  environment: ${file(./config/environment.yml):environment}
  
  # 👉 Provider-level IAM statements
  iam: ${file(./config/iam.yml):iam}

# Custom variables
custom: ${file(./config/custom.yml):custom}

functions: ${file(./config/functions.yml):functions}

resources:
  Resources: ${file(./config/resources.yml):Resources}
  
  Outputs:
    UserPoolId:
      Value: !Ref UserPool
    UserPoolClientId:
      Value: !Ref UserPoolClientSpa
    UserPoolArn:
      Value: !GetAtt UserPool.Arn
    ApiBase:
      Value: !Sub 'https://${ApiGatewayRestApi}.execute-api.${AWS::Region}.amazonaws.com'

