name: Backend CI

on:
  push: 
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'
    branches:
      - main
    pull_request:
      paths:
        - 'backend/**'

jobs:
  dev-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Install dependencies
        run: npm ci
      
      - name: Deploy dev stage
        run: npx serverless deploy --stage dev
      - name: Test all endpoints of deployed dev
        run: npm test

  prod-deploy:
    needs: dev-deploy
    if: success() && github.ref == 'refs/heads/main' 
    runs-on: ubuntu-lateset
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Install dependencies
        run: npm ci
      - name: Deploy to production stage
        run: npx serverless deploy --stage prod
      
